name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Delete previous artifacts (if any)
        run: |
          gh run list --json databaseId --jq '.[] | .databaseId' | while read id; do
            gh run delete $id --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure correct directory for upload
        run: |
          rm -rf ./public
          mkdir -p ./public
          rsync -av --progress . ./public --exclude={'.git*','node_modules','.github','.gitignore','artifact-*'}

      - name: Remove symlinks and hidden files
        run: |
          find ./public -type l -exec rm -f {} \;
          find ./public -type f -name ".*" -exec rm -f {} \;

      - name: Verify directory contents after cleanup
        run: |
          echo "Listing directory contents after cleanup..."
          ls -lah ./public
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.run_id }}
          path: './public'
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_id }}

      - name: Debug - List files after upload
        run: |
          echo "Listing files after upload..."
          ls -lah ./public
