name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Updated to latest version

      - name: Debug - List files
        run: ls -la  # Verify files before uploading

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Use correct artifact upload action
        with:
          path: './'  # Change if your static files are in a different folder (e.g., ./public)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Updated to latest version
